### ISSUE TITLE
Question: can I disable the auth or any connect to a server?

### ISSUE THREAD

**Issue by tscavoneGal** [jhhtaylor/tabstronaut#23]
Hi 👋 

Looks like a great extension!  Due to security reasons, I don't want my extension calling out to any 3rd party, I just want the group functionality.  Is there any way I can do that with tabstronaut?  

Thanks and congrats on what looks like a great extension!

**Comment by jhhtaylor** [comment]
@tscavoneGal I have removed the need for GitHub authentication. Please try Tabstronaut again and give feedback if you have any. 😊🧑‍🚀🪐
