### ISSUE TITLE
Log in with GitHub unable to connect

### ISSUE THREAD

**Issue by marcusviar** [jhhtaylor/tabstronaut#24]
When I click the **Log in with GitHub** button it loads http://localhost:3002/auth/github and says **Unable to connect**. I'm running Windows 10, VScode is up to date.

I've tried:

- Made sure there are no blocking firewall rules.
- Reinstalling Tabstronaut.
- Completely closing and reopening VScode.
- Loading in Firefox and Chrome.
- Shutting off my local dev server to make sure there were no conflicts.

Is there something I can do to fix this problem? Or make authentication optional for people that only want to use the extension on a single machine?

**Comment by jhhtaylor** [comment]
Hmm I am just on holiday now, but will investigate this when I get back. My guess is you have something still running on localhost:3002 but I could be wrong. 

Thanks for the message! 👩‍🚀🪐

**Comment by JusttCallMeMike** [comment]
omg, it is rly using local  3002 for auth? 
come on, we are developers, sure we have a ton of things running on popular local ports like that, would avoid anything on 3000-9999 ;)

**Comment by jhhtaylor** [comment]
@marcusviar @JusttCallMeMike 
I have removed the need for GitHub authentication, the extension should now work as expected. Please try using Tabstronaut again and give feedback if you have any.
