### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by ylazy** [jhhtaylor/tabstronaut#42]
Hi!
Thank you for a great extension!

I have some suggestions:

- Click on an item to open/focus on the file editor.
- ~~Adding an option to hide the file paths that are displaying right next to the file names.~~ ([not possible](https://github.com/microsoft/vscode/issues/81899))
- Display the file icon.
- Drag-drop a tab: Drag-in to add a tab to a group; Drag-out to remove a tab from a group. Drag up/down to change the tabs order.

Thank you!

**Comment by jhhtaylor** [comment]
Hello! 🌟

I'll definitely take a look at these ideas when I get a chance and consider implementing them in future updates. Your insights are very helpful in making the extension better.

Thanks again for taking the time to share your suggestions!

**Comment by ylazy** [comment]
After some research I think `Adding an option to hide the file paths that are displaying right next to the file names` [is not possible now](https://github.com/microsoft/vscode/issues/81899).

We have to do some hack to achieve this:
Install [Custom VSCode UI CSS](https://marketplace.visualstudio.com/items?itemName=kencocaceo.customvscodeuicss)
Use this css to hide the path:
```css
.customview-tree .monaco-icon-label>.monaco-icon-label-container>.monaco-icon-description-container>.label-description
{
	display:none
}
```
The result:

![image](https://github.com/jhhtaylor/tabstronaut/assets/6010183/3d1684c9-93a6-45b7-bb9b-26777ecf41c9)

I've updated the suggestion list with an additional suggestion: Drag-drop a tab to a group.

Thank you!

**Comment by jhhtaylor** [comment]
Hi @ylazy 
I added a few of these features in Release 1.1.8 of Tabstornaut,

> In this update, we added file icons based on the user's File Icon Theme, relative paths instead of absolute paths shown in Tab descriptions, the ability to click a Tab to restore it, and the ability to remove a single Tab from a Tab Group. Enjoy using Tabstronaut!

I didn't add the drag-and-drop as it is not possible within the VS Code Extension API. 
I didn't completely remove the path in the description, but it is now relative instead of absolute as this still provides useful information. 

Try it out and let me know if you have any additional thoughts.

**Comment by ylazy** [comment]
Hi @jhhtaylor 
It's much better than expected.

![image](https://github.com/jhhtaylor/tabstronaut/assets/6010183/24cd6124-963f-48d8-bc9f-fdc28992752a)

> I didn't add the drag-and-drop as it is not possible within the VS Code Extension API.

Do you mean it's not possible to drag a tab in the horizontal tab bar to the Tabstornaut region?
How about dragging an item up/down to change the tabs order and groups order?

I think it's worth to add these new features to the change log.
Thank so much!

**Comment by jhhtaylor** [comment]
Hi @ylazy,

I tried both the new file drag and re-arrange drag, both seem not to be possible. I will see if it becomes available in the future within the VS Code Extension API.

I agree it would be a convenient feature. 

Thanks again for the feedback! 🧑‍🚀🪐

**Comment by ylazy** [comment]
I don't know if this's useful or not but maybe [this extension](https://marketplace.visualstudio.com/items?itemName=jiapeiyao.tab-group) could give you some hints. With the Tab Group extension I can drag-drop files but if you close a file then it will be also gone in the group and I don't like how it work, so I uninstalled it and found your extension ;)

I think you won the award for the fastest updated extension of the day 🥇 
Thank you!

**Comment by jhhtaylor** [comment]
Interesting. I will investigate it 👍

**Comment by ylazy** [comment]
Hi! I've tried the latest version. So cool with the group color.

If it's possible, please consider adding a button in each group that allow us to hide/show the relative file paths.

The relative path provides useful information when I have at least two file that have the same name in different locations, but most of the time I don't need it, especially when I'm using/building a framework that each file has an unique name.

Or in this case where all files have the same location:

![image](https://github.com/jhhtaylor/tabstronaut/assets/6010183/34a679bc-b50b-4155-8d95-cf9b59afc657)

Thank you very much!

**Comment by jhhtaylor** [comment]
Christmas has come early in Release 1.1.11😎 
![image](https://github.com/jhhtaylor/tabstronaut/assets/29454433/d4cba3d7-a942-47c8-af64-b4aee2bcd9c8)

**Comment by ylazy** [comment]
Excellent!!!
Thanks!!!!!
