### ISSUE TITLE
[FEATURE REQUEST] List ungrouped tabs in the extension bar

### ISSUE THREAD

**Issue by cdipietro** [jhhtaylor/tabstronaut#50]
It would be nice to have all opened tabs listed in the extension sidebar to be able to quickly switch among them from there.

This is done in the [vscode-tab-group extension](https://github.com/billgoo/vscode-tab-group) which could serve as a reference.

**Comment by jhhtaylor** [comment]
The philosophy of [vscode-tab-group extension](https://github.com/billgoo/vscode-tab-group) is more like Microsoft Edge and has its place in regard to this matter. 'vscode-tab-group extension' only works on editor tabs currently active in VS Code.

Alternatively, Tabstronaut excels in tab management for VS Code by enabling users to **archive and retrieve** specific tab groups. It ensures frequently used or feature-specific tabs are systematically stored for future access. 

I do not feel this is the direction I want to go with Tabstronaut, but I might consider it in the future. 

Thank you for the feedback! 😎👍

**Comment by jhhtaylor** [comment]
The philosophy of [vscode-tab-group extension](https://github.com/billgoo/vscode-tab-group) is more like Microsoft Edge and has its place in regard to this matter. 'vscode-tab-group extension' only works on editor tabs currently active in VS Code.

Alternatively, Tabstronaut excels in tab management for VS Code by enabling users to **archive and retrieve** specific tab groups. It ensures frequently used or feature-specific tabs are systematically stored for future access. 

I do not feel this is the direction I want to go with Tabstronaut, but I might consider it in the future. 

Thank you for the feedback! 😎👍
