### ISSUE TITLE
[FEATURE REQUEST] Adding tabs to group through drag-and-drop

### ISSUE THREAD

**Issue by cdipietro** [jhhtaylor/tabstronaut#51]
It would be nice to have the ability to add opened tabs to any group by simply dragging and dropping the tab into the group in the extension sidebar.

This is done in the [vscode-tab-group extension](https://github.com/billgoo/vscode-tab-group) which could serve as a reference.

**Comment by jhhtaylor** [comment]
I do agree this would be a useful feature.

I do not feel this is the direction I want to go with Tabstronaut just yet, but I might consider it in the future. 

Thank you for the feedback! 😎👍

**Comment by jhhtaylor** [comment]
I do agree this would be a useful feature.

I do not feel this is the direction I want to go with Tabstronaut just yet, but I might consider it in the future. 

Thank you for the feedback! 😎👍
