### ISSUE TITLE
[FEATURE REQUEST] Reorder tabs within group through drag-and-drop

### ISSUE THREAD

**Issue by cdipietro** [jhhtaylor/tabstronaut#52]
As it works right now, you must recreate the entire group to achieve the desired tab order. It would be great to be able to reorder tabs within any group by simply dragging and dropping the listed files.

This is done in the [vscode-tab-group extension](https://github.com/billgoo/vscode-tab-group) which could serve as a reference.

**Comment by jhhtaylor** [comment]
I do agree this would be a useful feature.

I do not feel this is the direction I want to go with Tabstronaut just yet, but I might consider it in the future. 

Thank you for the feedback! 😎👍

**Comment by jhhtaylor** [comment]
I do agree this would be a useful feature.

I do not feel this is the direction I want to go with Tabstronaut just yet, but I might consider it in the future. 

Thank you for the feedback! 😎👍

**Comment by jhhtaylor** [comment]
I do agree this would be a useful feature.

I do not feel this is the direction I want to go with Tabstronaut just yet, but I might consider it in the future. 

Thank you for the feedback! 😎👍
