### ISSUE TITLE
[FEATURE REQUEST] Rearrange tabs groups

### ISSUE THREAD

**Issue by cdipietro** [jhhtaylor/tabstronaut#53]
It would be great to be able to reorder tab groups by simply dragging and dropping them into the desired order.

This is done in the [vscode-tab-group extension](https://github.com/billgoo/vscode-tab-group) through a "sort mode"  button that enables the capability of rearranging groups. I believe it could serve as a reference.

**Comment by jhhtaylor** [comment]
I do agree this would be a useful feature.

I do not feel this is the direction I want to go with Tabstronaut just yet, but I might consider it in the future. 

Thank you for the feedback! 😎👍

**Comment by jhhtaylor** [comment]
I do agree this would be a useful feature.

I do not feel this is the direction I want to go with Tabstronaut just yet, but I might consider it in the future. 

Thank you for the feedback! 😎👍
