### ISSUE TITLE
Incorrectly updated tab name after renaming

### ISSUE THREAD

**Issue by ylazy** [jhhtaylor/tabstronaut#56]
Hi! It's me again ;)

I'm facing a minor bug: When I renamed a class (file), the tab name has been updated incorrectly: The name has been turned into lower case. Please view the video for detail:

https://github.com/jhhtaylor/tabstronaut/assets/6010183/61416fc4-e71a-455c-8687-2601b80e352d

Have a nice day!

**Comment by jhhtaylor** [comment]
Updated in Release 1.1.15 😎

Thanks for the feedback! It only makes Tabstronaut better.

![Motivational-Bill-Gates-Quote](https://github.com/jhhtaylor/tabstronaut/assets/29454433/714a3afa-563d-485d-862e-f713f84204dc)
