### ISSUE TITLE
Error when using command "Restore tab group"

### ISSUE THREAD

**Issue by hervehobbes** [jhhtaylor/tabstronaut#63]
Hello,

First, thank you very much for this useful extension.
I just created a group of tabs and wanted to restore them so I used the "Restore tab group" command but this error appears :

Command 'Tabstronaut: Restore Tab Group' resulted in an error
Cannot read properties of undefined (reading 'contextValue')

I'm using Tabstronaut version 1.1.16 with VS Code version  1.83.1.

In the Runtime status panel I have this :
Activation Event:onCommand:tabstronaut.openTabGroupContextMenu

And:
Uncaught Errors (3)
Cannot read properties of undefined (reading 'contextValue')

Thank you in advance for any help

**Comment by jhhtaylor** [comment]
Hi @hervehobbes 
Thanks for for the kind words and reporting the issue!

Okay, I see this error - Did you use the command from the command palette? I didn't test these much - will look at implementing a solution 👍🏻
![image](https://github.com/jhhtaylor/tabstronaut/assets/29454433/737c0b9f-4224-434b-a0c4-fe17b9b194dc)

For now, rather use this button on the Tab Group:
![Screenshot 2023-10-29 at 20 47 45](https://github.com/jhhtaylor/tabstronaut/assets/29454433/daa1c627-c0ca-42e3-a274-ca8bca2b7047)

**Comment by jhhtaylor** [comment]
An update: I removed the Command Palette options - I feel they weren't used enough to try to add a fix. Please use the button on the tab group instead 👍

**Comment by hervehobbes** [comment]
ah, that's a shame, I do everything on the keyboard.

**Comment by jhhtaylor** [comment]
**You can use Keyboard shortcuts to open tab groups:**
[Instantly Restore Tab Groups with Keybindings](https://github.com/jhhtaylor/tabstronaut#instantly-restore-tab-groups-with-keybindings)
Tabstronaut now supports keybindings to swiftly restore tab groups. Here's how to make the most out of them:

Restore the First Tab Group: Ctrl+Alt+1 (or Cmd+Alt+1 on macOS)
Restore the Second Tab Group: Ctrl+Alt+2 (or Cmd+Alt+2 on macOS)
Restore the Third Tab Group: Ctrl+Alt+3 (or Cmd+Alt+3 on macOS)
... and so on, up to the ninth group with Ctrl+Alt+9 (or Cmd+Alt+9 on macOS).

You can also open the context menu (to add tabs) with Ctrl+Alt+A
